         /**
         * Write a description of class DataWarehouse here.
         *
         * @author (your nombre)
         * @version (a version number or a date)
         */
        public class DataWarehouse
        {
            // instance variables - replace the example below with your own
           public static String animalHombreNombre(){
                String nombreH = "";
                int h = Randomizer.nextInt(1, 100);
                switch (h) {
case 1: nombreH = "ANTONIO";
    break;
case 2: nombreH = "MANUEL";
    break;
case 3: nombreH = "JOSE";
    break;
case 4: nombreH = "FRANCISCO";
    break;
case 5: nombreH = "DAVID";
    break;
case 6: nombreH = "JUAN";
    break;
case 7: nombreH = "JOSE ANTONIO";
    break;
case 8: nombreH = "JAVIER";
    break;
case 9: nombreH = "DANIEL";
    break;
case 10: nombreH = "JOSE LUIS";
    break;
case 11: nombreH = "FRANCISCO JAVIER";
    break;
case 12: nombreH = "CARLOS";
    break;
case 13: nombreH = "JESUS";
    break;
case 14: nombreH = "ALEJANDRO";
    break;
case 15: nombreH = "MIGUEL";
    break;
case 16: nombreH = "JOSE MANUEL";
    break;
case 17: nombreH = "RAFAEL";
    break;
case 18: nombreH = "MIGUEL ANGEL";
    break;
case 19: nombreH = "PEDRO";
    break;
case 20: nombreH = "PABLO";
    break;
case 21: nombreH = "ANGEL";
    break;
case 22: nombreH = "SERGIO";
    break;
case 23: nombreH = "JOSE MARIA";
    break;
case 24: nombreH = "FERNANDO";
    break;
case 25: nombreH = "JORGE";
    break;
case 26: nombreH = "LUIS";
    break;
case 27: nombreH = "ALBERTO";
    break;
case 28: nombreH = "JUAN CARLOS";
    break;
case 29: nombreH = "ALVARO";
    break;
case 30: nombreH = "ADRIAN";
    break;
case 31: nombreH = "JUAN JOSE";
    break;
case 32: nombreH = "DIEGO";
    break;
case 33: nombreH = "RAUL";
    break;
case 34: nombreH = "IVAN";
    break;
case 35: nombreH = "JUAN ANTONIO";
    break;
case 36: nombreH = "RUBEN";
    break;
case 37: nombreH = "ENRIQUE";
    break;
case 38: nombreH = "OSCAR";
    break;
case 39: nombreH = "RAMON";
    break;
case 40: nombreH = "VICENTE";
    break;
case 41: nombreH = "ANDRES";
    break;
case 42: nombreH = "JUAN MANUEL";
    break;
case 43: nombreH = "JOAQUIN";
    break;
case 44: nombreH = "SANTIAGO";
    break;
case 45: nombreH = "VICTOR";
    break;
case 46: nombreH = "EDUARDO";
    break;
case 47: nombreH = "MARIO";
    break;
case 48: nombreH = "ROBERTO";
    break;
case 49: nombreH = "JAIME";
    break;
case 50: nombreH = "FRANCISCO JOSE";
    break;
case 51: nombreH = "MARCOS";
    break;
case 52: nombreH = "IGNACIO";
    break;
case 53: nombreH = "ALFONSO";
    break;
case 54: nombreH = "JORDI";
    break;
case 55: nombreH = "HUGO";
    break;
case 56: nombreH = "RICARDO";
    break;
case 57: nombreH = "SALVADOR";
    break;
case 58: nombreH = "GUILLERMO";
    break;
case 59: nombreH = "EMILIO";
    break;
case 60: nombreH = "GABRIEL";
    break;
case 61: nombreH = "MARC";
    break;
case 62: nombreH = "GONZALO";
    break;
case 63: nombreH = "JULIO";
    break;
case 64: nombreH = "JULIAN";
    break;
case 65: nombreH = "MOHAMED";
    break;
case 66: nombreH = "JOSE MIGUEL";
    break;
case 67: nombreH = "TOMAS";
    break;
case 68: nombreH = "MARTIN";
    break;
case 69: nombreH = "AGUSTIN";
    break;
case 70: nombreH = "JOSE RAMON";
    break;
case 71: nombreH = "NICOLAS";
    break;
case 72: nombreH = "ISMAEL";
    break;
case 73: nombreH = "JOAN";
    break;
case 74: nombreH = "FELIX";
    break;
case 75: nombreH = "SAMUEL";
    break;
case 76: nombreH = "CRISTIAN";
    break;
case 77: nombreH = "AITOR";
    break;
case 78: nombreH = "LUCAS";
    break;
case 79: nombreH = "HECTOR";
    break;
case 80: nombreH = "JUAN FRANCISCO";
    break;
case 81: nombreH = "IKER";
    break;
case 82: nombreH = "JOSEP";
    break;
case 83: nombreH = "JOSE CARLOS";
    break;
case 84: nombreH = "ALEX";
    break;
case 85: nombreH = "MARIANO";
    break;
case 86: nombreH = "DOMINGO";
    break;
case 87: nombreH = "SEBASTIÁN";
    break;
case 88: nombreH = "ALFREDO";
    break;
case 89: nombreH = "CESAR";
    break;
case 90: nombreH = "JOSE ANGEL";
    break;
case 91: nombreH = "FELIPE";
    break;
case 92: nombreH = "JOSE IGNACIO";
    break;
case 93: nombreH = "VICTOR MANUEL";
    break;
case 94: nombreH = "RODRIGO";
    break;
case 95: nombreH = "LUIS MIGUEL";
    break;
case 96: nombreH = "MATEO";
    break;
case 97: nombreH = "JOSE FRANCISCO";
    break;
case 98: nombreH = "JUAN LUIS";
    break;
case 99: nombreH = "XAVIER";
    break;
case 100: nombreH = "ALBERT";
    break;

                }
                return nombreH;
            }
           public static String animalMujerNombre(){
               String nombreM = "";
               int m = Randomizer.nextInt(1, 100);
                switch (m) {
case 1: nombreM = "MARIA CARMEN";
        break;
case 2: nombreM = "MARIA";
        break;
case 3: nombreM = "CARMEN";
        break;
case 4: nombreM = "ANA MARIA";
        break;
case 5: nombreM = "JOSEFA";
        break;
case 6: nombreM = "ISABEL";
        break;
case 7: nombreM = "MARIA PILAR";
        break;
case 8: nombreM = "MARIA DOLORES";
        break;
case 9: nombreM = "LAURA";
        break;
case 10: nombreM = "MARIA TERESA";
    break;
case 11: nombreM = "ANA";
    break;
case 12: nombreM = "CRISTINA";
    break;
case 13: nombreM = "MARTA";
    break;
case 14: nombreM = "MARIA ANGELES";
    break;
case 15: nombreM = "FRANCISCA";
    break;
case 16: nombreM = "LUCIA";
    break;
case 17: nombreM = "MARIA ISABEL";
    break;
case 18: nombreM = "MARIA JOSE";
    break;
case 19: nombreM = "ANTONIA";
    break;
case 20: nombreM = "DOLORES";
    break;
case 21: nombreM = "SARA";
    break;
case 22: nombreM = "PAULA";
    break;
case 23: nombreM = "ELENA";
    break;
case 24: nombreM = "MARIA LUISA";
    break;
case 25: nombreM = "RAQUEL";
    break;
case 26: nombreM = "ROSA MARIA";
    break;
case 27: nombreM = "PILAR";
    break;
case 28: nombreM = "CONCEPCION";
    break;
case 29: nombreM = "MANUELA";
    break;
case 30: nombreM = "MARIA JESUS";
    break;
case 31: nombreM = "MERCEDES";
    break;
case 32: nombreM = "JULIA";
    break;
case 33: nombreM = "BEATRIZ";
    break;
case 34: nombreM = "NURIA";
    break;
case 35: nombreM = "SILVIA";
    break;
case 36: nombreM = "ROSARIO";
    break;
case 37: nombreM = "JUANA";
    break;
case 38: nombreM = "ALBA";
    break;
case 39: nombreM = "IRENE";
    break;
case 40: nombreM = "TERESA";
    break;
case 41: nombreM = "ENCARNACION";
    break;
case 42: nombreM = "PATRICIA";
    break;
case 43: nombreM = "MONTSERRAT";
    break;
case 44: nombreM = "ANDREA";
    break;
case 45: nombreM = "ROCIO";
    break;
case 46: nombreM = "MONICA";
    break;
case 47: nombreM = "ROSA";
    break;
case 48: nombreM = "ALICIA";
    break;
case 49: nombreM = "MARIA MAR";
    break;
case 50: nombreM = "SONIA";
    break;
case 51: nombreM = "SANDRA";
    break;
case 52: nombreM = "ANGELA";
    break;
case 53: nombreM = "MARINA";
    break;
case 54: nombreM = "SUSANA";
    break;
case 55: nombreM = "NATALIA";
    break;
case 56: nombreM = "YOLANDA";
    break;
case 57: nombreM = "MARGARITA";
    break;
case 58: nombreM = "MARIA JOSEFA";
    break;
case 59: nombreM = "CLAUDIA";
    break;
case 60: nombreM = "EVA";
    break;
case 61: nombreM = "MARIA ROSARIO";
    break;
case 62: nombreM = "INMACULADA";
    break;
case 63: nombreM = "SOFIA";
    break;
case 64: nombreM = "MARIA MERCEDES";
    break;
case 65: nombreM = "CARLA";
    break;
case 66: nombreM = "ANA ISABEL";
    break;
case 67: nombreM = "ESTHER";
    break;
case 68: nombreM = "NOELIA";
    break;
case 69: nombreM = "VERONICA";
    break;
case 70: nombreM = "ANGELES";
    break;
case 71: nombreM = "NEREA";
    break;
case 72: nombreM = "CAROLINA";
    break;
case 73: nombreM = "MARIA VICTORIA";
    break;
case 74: nombreM = "EVA MARIA";
    break;
case 75: nombreM = "INES";
    break;
case 76: nombreM = "MIRIAM";
    break;
case 77: nombreM = "MARIA ROSA";
    break;
case 78: nombreM = "DANIELA";
    break;
case 79: nombreM = "LORENA";
    break;
case 80: nombreM = "ANA BELEN";
    break;
case 81: nombreM = "MARIA ELENA";
    break;
case 82: nombreM = "MARIA CONCEPCION";
    break;
case 83: nombreM = "VICTORIA";
    break;
case 84: nombreM = "AMPARO";
    break;
case 85: nombreM = "MARIA ANTONIA";
    break;
case 86: nombreM = "CATALINA";
    break;
case 87: nombreM = "MARTINA";
    break;
case 88: nombreM = "LIDIA";
    break;
case 89: nombreM = "ALEJANDRA";
    break;
case 90: nombreM = "CELIA";
    break;
case 91: nombreM = "MARIA NIEVES";
    break;
case 92: nombreM = "CONSUELO";
    break;
case 93: nombreM = "OLGA";
    break;
case 94: nombreM = "AINHOA";
    break;
case 95: nombreM = "FATIMA";
    break;
case 96: nombreM = "GLORIA";
    break;
case 97: nombreM = "EMILIA";
    break;
case 98: nombreM = "MARIA SOLEDAD";
    break;
case 99: nombreM = "CLARA";
    break;
case 100: nombreM = "MARIA CRISTINA";
    break;

        }
        return nombreM;
    }
    static int y;
    static int z;
    static int p;
    static int x;
    static int f;
    public static String tipoAnimalM(){
        String tipoM = "";
        x = Randomizer.nextInt(1, 15);
        if (x == 15){
            int u = Randomizer.nextInt(1, 50);
            if (u == 1){
                x = 15;
            }else{
                x = Randomizer.nextInt(1, 14);
            }
        }
        switch (x) {
case 1: tipoM = "Vaca";
        y = 40;
        z = 1;
        p = 900;
        f =  65;
    break;
case 2: tipoM = "Perra";
        y = 80;
        z = 2;
        p = 90;
        f =  45;
    break;
case 3: tipoM = "Gata";
        y = 90;
        z = 3;
        p = 90;
        f =  30;
    break;
case 4: tipoM = "Yegua";
        y = 70;
        z = 4;
        p = 400;
        f =  75;
    break;
case 5: tipoM = "Gallina";
        y = 30;
        z = 5;
        p = 50;
        f =  25;
    break;
case 6: tipoM = "Oveja";
        y = 50;
        z = 6;
        p = 200;
        f =  35;
    break;
case 7: tipoM = "Cerda";
        y = 100;
        z = 7;
        p = 250;
        f =  30;
    break;
case 8: tipoM = "Asna/Burra";
        y = 85;
        z = 8;
        p = 350;
        f =  70;
    break;
case 9: tipoM = "Mula";
        y = 80;
        z = 9;
        p = 290;
        f =  75;
    break;
case 10: tipoM = "Pata";
        y = 20;
        z = 10;
        p = 40;
        f =  25;
    break;
case 11: tipoM = "Gansa";
        y = 50;
        z = 11;
        p = 60;
        f =  35;
    break;
case 12: tipoM = "Pava";
        y = 20;
        z = 12;
        p = 70;
        f =  30;
    break;
case 13: tipoM = "Cabra";
        y = 50;
        z = 13;
        p = 150;
        f =  50;
    break;
case 14: tipoM = "Coneja";
        y = 55;
        z = 15;
        p = 15;
        f =  20;
    break;
case 15: tipoM = "Unicornia";
        y = 1000;
        z = 16;
        f =  45;
        f =  10000;
    break;

        }
        return tipoM;
    }
    
    public static String tipoAnimalH(){
        String tipoH = "";
        x = Randomizer.nextInt(1, 15);
        if (x == 15){
            int u = Randomizer.nextInt(1, 50);
            if (u == 1){
                x = 15;
            }else{
                x = Randomizer.nextInt(1, 14);
            }
        }
        switch (x) {
            case 1: tipoH = "Toro/Bueye";
                    y = 40;
                    z = 17;
                    p = 900;
                    f =  85;
    break;
case 2: tipoH = "Perro";
        y = 80;
        z = 2;
        p = 90;
        f =  50;
    break;
case 3: tipoH = "Gato";
        y = 90;
        z = 3;
        p = 90;
        f =  30;
    break;
case 4: tipoH = "Caballo";
        y = 70;
        z = 4;
        p = 400;
        f =  80;
    break;
case 5: tipoH = "Gallo";
        y = 30;
        z = 14;
        p = 40;
        f =  25;
    break;
case 6: tipoH = "Carnero";
        y = 50;
        z = 6;
        p = 150;
        f =  45;
    break;
case 7: tipoH = "Cerdo";
        y = 100;
        z = 7;
        p = 150;
        f =  35;
    break;
case 8: tipoH = "Asno/Burro";
        y = 85;
        z = 8;
        p = 350;
        f =  75;
    break;
case 9: tipoH = "Mulo";
        y = 80;
        z = 9;
        p = 290;
        f =  80;
    break;
case 10: tipoH = "Pato";
        y = 20;
        z = 10;
        p = 40;
        f =  30;
    break;
case 11: tipoH = "Ganso";
        y = 50;
        z = 11;
        p = 60;
        f =  40;
    break;
case 12: tipoH = "Pavo";
        y = 20;
        z = 12;
        p = 70;
        f =  35;
    break;
case 13: tipoH = "Cabrón";
        y = 50;
        z = 13;
        p = 130;
        f =  55;
    break;
case 14: tipoH = "Conejo";
        y = 55;
        z = 15;
        p = 15;
        f =  20;
    break;
case 15: tipoH = "Unicornio";
        y = 1000;
        z = 16;
        f =  10000;
    break;

        }
        
        return tipoH;
    }
    static int e;
    public static String tipoAnimalEng(){
        String type = "";
        switch (z) {
case 1: type = "Cow";
        e = 2;
    break;
case 2: type = "Dog";
        e = 1;
    break;
case 3: type = "Cat";
        e = 1;
    break;
case 4: type = "Horse";
        e = 2;
    break;
case 5: type = "Chicken";
        e = 1;
    break;
case 6: type = "Sheep";
        e = 1;
    break;
case 7: type = "Pig";
        e = 1;
    break;
case 8: type = "Donkey";
        e = 3;
    break;
case 9: type = "Mule";
        e = 0;
    break;
case 10: type = "Duck";
        e = 1;
    break;
case 11: type = "Goose";
        e = 1;
    break;
case 12: type = "Turkey";
        e = 2;
    break;
case 13: type = "Goat";
        e = 2;
    break;
case 14: type = "Rooster";
        e = 1;
    break;
case 15: type = "Bunny";
        e = 1;
    break;
case 16: type = "Unicorn";
        e = 100;
    break;
case 17: type = "Bull";
        e = 2;
    break;

        }
        return type;
    }
    public static int inteligencia(){
        return y;
    }
    public static int maduridad(){
        return e;
    }
    public static int precio(){
        return p;
    }
    public static int fuerza(){
        return f;
    }
}